/**
 * One-off generator: reads flash_blog_legal_posts.md and writes lib/content/blog-posts-data.ts
 * Usage: npx tsx scripts/parse-blog-posts.ts [path-to-md]
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const mdPath =
  process.argv[2] ??
  resolve(
    process.env.USERPROFILE ?? "",
    "Downloads",
    "flash_blog_legal_posts.md",
  );

const md = readFileSync(mdPath, "utf-8");

/** Strip cold-email launch promo (9/30 free) — not for public blog. */
function sanitizeBlogContent(content: string): string {
  let text = content;

  const patterns: RegExp[] = [
    /\*\*🔥[^\n]*\*\*\n?/g,
    /即日起至今年\s*\*\*9\s*月\s*30\s*日前[^*]*\*\*！?/g,
    /Flash 即日起至今年\s*\*\*9\s*月\s*30\s*日前[^*]*\*\*！?/g,
    /Flash is \*\*100% FREE[^*]*\*\*[^[\n]*(?=\[)/gi,
    /Flashは\*\*今年の9月30日まで[^*]*\*\*[^[\n]*(?=\[)/g,
    /Flashは\*\*今年の9月30日まで[^*]*\*\*[^。]*。/g,
    /Flash는 \*\*올해 9월 30일까지[^*]*\*\*[^[\n]*(?=\[)/g,
    /Flash는 \*\*올해 9월 30일까지[^*]*\*\*[^.]*\.\s*/g,
    /Flash es \*\*100% GRATUIT[^*]*\*\*[^[\n]*(?=\[)/gi,
    /Todas las funciones de Flash son \*\*100% GRATUITAS[^*]*\*\*[^[\n]*(?=\[)/gi,
    /o Flash está \*\*100% GRATUITO[^*]*\*\*[^[\n]*(?=\[)/gi,
    /ist Flash \*\*bis zum 30\. September[^*]*\*\*[^[\n]*(?=\[)/gi,
    /Flash ist \*\*bis zum 30\. September[^*]*\*\*[^[\n]*(?=\[)/gi,
    /Flash est \*\*100% GRATUIT[^*]*\*\*[^[\n]*(?=\[)/gi,
    /L'accès à Flash est \*\*100% GRATUIT[^*]*\*\*[^[\n]*(?=\[)/gi,
    /Flash เปิดให้ใช้งาน[^[\n]*30 กันยายน[^[\n]*(?=\[)/g,
    /Protect your hustle and secure your studio today\.\s*/gi,
    /To empower artists to reclaim their creative rights,\s*/gi,
    /為協助獨立刺青師打造安全的創作環境，/g,
    /保護你的工作室，從今天開始。/g,
    /アーティストの創作権を守るため、/g,
    /リスクからスタジオを守り、プロとしてのビジネスを確立しましょう。/g,
    /아티스트의 창작 권리를 보장하기 위해,\s*/g,
    /스튜디오의 안전 자산을 지금 구축하세요\.\s*/g,
    /Para apoyar a los artistas independientes,\s*/gi,
    /Protege tu negocio y asegura tu estudio desde hoy\.\s*/gi,
    /Para fortalecer os artistas independentes,\s*/gi,
    /Proteja o seu ganha-pão[^.]*\.\s*/gi,
    /Um die Rechte von Tattoo-Künstlern zu stärken,\s*/gi,
    /Schütze deine Existenz und professionalisiere dein Studio noch heute\.\s*/gi,
    /Pour soutenir la communauté des tatoueurs indépendants,\s*/gi,
    /Sécurisez votre gagne-pain[^.]*\.\s*/gi,
    /เพื่อสนับสนุนสิทธิ์ในการสร้างสรรค์ของช่างสักอิสระ\s*/g,
    /ปกป้องร้านและธุรกิจของคุณตั้งแต่วันนี้\s*/g,
  ];

  for (const pattern of patterns) {
    text = text.replace(pattern, "");
  }

  return text.replace(/\n{3,}/g, "\n\n").trim();
}

const localeMap: Record<string, string> = {
  "zh-TW": "zh-Hant",
  en: "en",
  ja: "ja",
  ko: "ko",
  es: "es",
  pt: "pt-BR",
  de: "de",
  fr: "fr",
  th: "th",
};

type PostLocaleContent = {
  title: string;
  summary: string;
  content: string;
};

type BlogPost = {
  slug: string;
  category: string;
  locales: Record<string, PostLocaleContent>;
};

const posts: BlogPost[] = [];

const articleBlocks = md.split(/## =+\n## ARTICLE ID: /).slice(1);

for (const block of articleBlocks) {
  const idMatch = block.match(/^([^\n]+)/);
  if (!idMatch) continue;
  const slug = idMatch[1].trim();

  const categoryMatch = block.match(
    /## (?:DEFAULT )?CATEGORY: ([^\n]+)/,
  );
  const category = categoryMatch?.[1]?.trim() ?? "Blog";

  const locales: Record<string, PostLocaleContent> = {};

  const langSections = block.split(/### >>> LANGUAGE: /).slice(1);
  for (const section of langSections) {
    const langMatch = section.match(/^([^\s]+) <<<\n/);
    if (!langMatch) continue;
    const rawLang = langMatch[1].trim();
    const locale = localeMap[rawLang];
    if (!locale) {
      console.warn(`Unknown language tag: ${rawLang}`);
      continue;
    }

    const titleMatch = section.match(/\*\*Title:\*\* (.+)/);
    const summaryMatch = section.match(/\*\*Summary:\*\* (.+)/);
    const bodyMatch = section.match(
      /\*\*Body Content:\*\*\n\n([\s\S]*?)(?=\n---\s*\n\n(?:### >>> LANGUAGE:|## =+)|$)/,
    );

    if (!titleMatch || !summaryMatch || !bodyMatch) {
      console.warn(`Missing fields for ${slug} / ${rawLang}`);
      continue;
    }

    locales[locale] = {
      title: titleMatch[1].trim(),
      summary: summaryMatch[1].trim(),
      content: sanitizeBlogContent(bodyMatch[1].trim()),
    };
  }

  posts.push({ slug, category, locales });
}

const outPath = resolve(process.cwd(), "lib/content/blog-posts-data.ts");
const output = `// AUTO-GENERATED by scripts/parse-blog-posts.ts — do not edit by hand.

export const blogPostsData = ${JSON.stringify(posts, null, 2)} as const;
`;

writeFileSync(outPath, output, "utf-8");
console.log(`Wrote ${posts.length} posts to ${outPath}`);
